# Create SSA EC2 Security Group within the VPC 
- name: Create EC2 security group
  ec2_group:
    name: "{{ security_group_name }}"
    tags:
      Name: "{{ security_group_name }}"
    description: "{{ security_group_description }}"
    region: "{{ ec2_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ hostvars['localhost'].vpc.vpc.id }}"
    rules:
      - proto: tcp
        ports:
          - 22
          - 80
          - 443
        cidr_ip: 0.0.0.0/0
  register: aws_sg_ec2

# Create SSA Load Balancer Security Group
- name: Create Load Balancer Security Group
  ec2_group:
    name: "SSA Load Balancer SG"
    tags:
      Name: "SSA Load Balancer SG"
    description: "Port 80, 443"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    state: "present"
  register: my_lb_group

- name: Set Load Balancer Security Group ID in variable
  set_fact:
    lb_group_id: "{{ my_lb_group.group_id }}"